[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
auto_detect_remappings = true
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
fuzz_runs = 1_000

[rpc_endpoints]
ethereum_sepolia = "${ETHEREUM_SEPOLIA_RPC}"
ethereum_mainnet = "${ETHEREUM_MAINNET_RPC}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[profile.ci]
fuzz_runs = 100_000

[fmt] # See https://book.getfoundry.sh/reference/config/formatter
tab_width = 2
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

#https://github.com/foundry-rs/foundry/tree/master/crates/config
